
/*
	String.h
	This msg file was autogenerated by the Rutgers avr_bridge software.
	*/ 
#ifndef STRING_H
#define STRING_H
#include "Msg.h"
#include "vector.h"
#include "ros_string.h"


namespace std_msgs {
class String : public Msg{
   public:
	String();
	String(uint8_t * data);
	~String();

	uint16_t bytes();
	uint16_t serialize(uint8_t * out_buffer);
	uint16_t deserialize(uint8_t * data);

	ROS::string data;
   private:

}; /***** ending class String *******/


} /***** ending namespace std_msgs *******/

#endif  /****   STRING_H    *****/
