
/*
	RazorImu.h
	This msg file was autogenerated by the Rutgers avr_bridge software.
	*/ 
#ifndef RAZORIMU_H
#define RAZORIMU_H
#include "Msg.h"
#include "vector.h"
#include "ros_string.h"
#include "Vec3.h"
#include "Vec3.h"


namespace imu_9drazor {
class RazorImu : public Msg{
   public:
	RazorImu();
	RazorImu(uint8_t * data);
	~RazorImu();

	virtual uint16_t bytes();
	virtual uint16_t serialize(uint8_t * out_buffer);
	virtual uint16_t deserialize(uint8_t * data);

	imu_9drazor::Vec3 angular_velocity;
	imu_9drazor::Vec3 linear_acceleration;
	float roll;
	float pitch;
	float yaw;
   private:

}; /***** ending class RazorImu *******/


} /***** ending namespace imu_9drazor *******/

#endif  /****   RAZORIMU_H    *****/