/*
 * Ros.h
 *
 * Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Adam Stambler
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Adam Stambler, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */

#ifndef ROS_H_
#define ROS_H_
#include "ros_string.h"
#include "Msg.h"

#include <stdio.h>
#include <stdbool.h>
#include <stdint.h>

#define __deprecated __attribute__((deprecated))

#ifndef UINT8_MAX
#define UINT8_MAX 0xff
#endif

#define ROS_BUFFER_SIZE (UINT8_MAX + 1)
typedef void (*ros_cb)(Msg *msg);

struct PktHeader {
		uint8_t packet_type;
#define PT_TOPIC	(0)
#define PT_SERVICE	(1)
#define PT_GETID	(0xff)
		uint8_t topic_tag;
		uint16_t msg_length;
};

typedef uint8_t Publisher;

struct RosInputCtx {
	RosInputCtx(uint8_t _topic_tag_max);
	bool append(char c);
	void reset(void) {
		buffer_index = 0;
	}

	/* only used for a sanity check */
	uint8_t topic_tag_max;


	/* buffer incomming chars. */
	union {
		uint8_t buffer[ROS_BUFFER_SIZE];
		/* convenient access to the buffer */
		PktHeader header;
	};

	uint8_t buffer_index;
};

class Ros {
public:
	__deprecated
	Ros(char const *node_name, uint8_t num_of_msg_types);

	Ros(char const *node_name, uint8_t num_of_msg_types, FILE *_io);

	//initCommunication is a hook for user implemented code
	// this code should set up user implemented
	// ros_putchar/ros_getchar functions
	void initCommunication();

	//Get the publisher for a topic
	//You cannot advertise a topic that was not in the configuration
	//file
	Publisher advertise(char const *topic);

	void publish(Publisher pub, Msg *msg);
	void subscribe(char const *name, ros_cb funct, Msg *msg);

	void spin(char c);

	__deprecated
	void spin();

	~Ros();
private:
	FILE *io;

	ROS::string name;

	ros_cb cb_list[10];
	Msg *msg_list[10];
	uint8_t outBuffer[ROS_BUFFER_SIZE];

	void getID();
	void process_pkt();

	/* XXX: use an enum for pkt_type and topic to prevent swapping? */
	void send_pkt(uint8_t pkt_type, uint8_t topic,
			uint8_t const *data, uint8_t data_len);

	/* given the character string of a topic, determines the numeric tag to
	 * place in a packet */
	char getTopicTag(char const *topic);

	RosInputCtx in_ctx;
};

/* Declaration is generated by the C++ code generation scripts, see
 * ros_generated.cpp */
extern Ros ros;


#endif /* ROS_H_ */
